name: Deploy CLI Workspace CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy libraries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Install projects deps
        run: npm run "install projects deps"

      - name: Build all projects
        run: npm run "build all"

      - name: Replace README.md in main libraries
        run: |
          cp README.md dist/cli/
          cp README.md dist/core/

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Define an exclusion list
          EXCLUDED=("demo")

          # Dynamically build the array of library names, excluding the ones in EXCLUDED
          LIBRARIES=($(ls dist | grep -v -E "$(IFS=\|; echo "${EXCLUDED[*]}")"))

          echo "Libraries to publish: ${LIBRARIES[@]}"

          for LIB_NAME in "${LIBRARIES[@]}"; do
            DIR="./dist/$LIB_NAME"
            if [ -f "$DIR/package.json" ]; then
              echo "Publishing $LIB_NAME..."
              cd $DIR
              npm publish --access public || echo "Failed to publish $LIB_NAME, skipping..."
              cd ../..
            else
              echo "Skipping $LIB_NAME: package.json not found in $DIR"
            fi
          done
